### PR TITLE
doc: Add Yi as a notary meeting notes maintainer

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>

### CODE REVIEW

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by toddysm** [comment]
Closing as it is overwritten by #12

**Pull request closed without merging**
